### ISSUE TITLE
performance data value "U" is wrongly detected as invalid

### ISSUE THREAD

**Issue by daku3649** [lingej/pnp4nagios#118]
E.g. performance data

mytestvalue=U

This is valid performance data according to "Nagios Plugin Development Guidelines"
https://nagios-plugins.org/doc/guidelines.html#AEN200

'value may be a literal "U" instead, this would indicate that the actual value couldn't be determined'

But pnp4nagios says in it's perfdata.log:
"Invalid Perfdata detected"
for the above performance data.

**Comment by lingej** [comment]
Patches are welcome!

Please provide a patch and i will do the review

Joerg

**Comment by lingej** [comment]
https://github.com/lingej/pnp4nagios/blob/master/scripts/process_perfdata.pl.in#L919
U is valid!
