### ISSUE TITLE
Bulk mode with NPCD, Nagios stops logging if perfdata file is moved or does not exist

### ISSUE THREAD

**Issue by wltjr** [lingej/pnp4nagios#121]
I had allot of problems getting things setup, as this is really not valid.

This is bad, it moves the file and causes nagios to stop once the file no longer exists, basically does not work.
command_line    /bin/mv /usr/local/pnp4nagios/var/host-perfdata /usr/local/pnp4nagios/var/spool/host-perfdata.$TIMET$

This is not the cleanest, but it is a working solution. I switched to cp vs mv. Then I added a bit onto the end to make the file empty again.
command_line /bin/cp /usr/local/pnp4nagios/var/host-perfdata /usr/local/pnp4nagios/var/spool/host-perfdata.$TIMET$ && /bin/echo "" > /usr/local/pnp4nagios/var/host-perfdata

This way the file is never deleted or moved, just its contents emptied. This allows nagios to keep working and outputting performance data to the file. Likely need to update wiki and included samples accordingly. I can submit a PR if need be, but it will not address the website, just the sample. Thus creating a ticket/opening an issue.

**Comment by lingej** [comment]
this is not an pnp4nagios issue

**Comment by wltjr** [comment]
Yes it is a pnp4nagios issue as the docs and included example do not work. Thus the docs and examples need to be updated.

https://docs.pnp4nagios.org/pnp-0.6/config#bulk_mode_with_npcd
https://github.com/lingej/pnp4nagios/blob/master/sample-config/misccommands.cfg-sample.in

As stated in my original comments, the wiki and included samples need to be updated accordingly.

**Comment by lingej** [comment]
Please ask nagios enterprises to fix this ;)

If nagios stops working its an nagios issue

Good luck

**Comment by wltjr** [comment]
If your moving files a program A is creating for another program B is is NOT the first program A's fault, it is program B. Or the process of how things are done for program B. Many programs will stop writing to files if something happens to them, log files, etc. This is no different and it is not an issue with the program. This is a procedural issue. How pnp4nagios is instructing people to get data for pnp4nagios is wrong. It causes problems for a dependent program, nagios in this case. I really fail to see why modifying a command is such an issue.

I have resolved this issue for myself. The idea was to help others and to find a better way to do something. You are welcome to continue doing things incorrectly and showing the wrong way to do something. Which causes problems for another program you can blame, but it is not at fault by any means. Again the above links are not on nagios website. The commands in the sample are not how they are shipped with nagios.

Fix it or not is moot to me. I have already corrected this, after wasting considerable time in setting up pnp4nagios, just because of this one issue. The reluctance to address, and blaming nagios is quite humorous.
