### ISSUE TITLE
PHP 7 support

### ISSUE THREAD

**Issue by nacc** [lingej/pnp4nagios#125]
Hello,

What is, if any, the plans for PHP 7 support? kohana only with 3.3 and greater has PHP 7.0 support, and it seems like the dependency in pnp4nagios is (possibly) on older kohana versions? Ubuntu 16.04 is going to (hopefully) only support PHP 7, so I would like to understand if it's reasonable for us to simply not build pnp4nagios-web there, as it currently depends on libkohana2 (which definitely doesn't support PHP7).

Thanks!
-Nish

**Comment by lingej** [comment]
There are no plans to support php7

**Comment by nacc** [comment]
Thanks!

**Comment by calestyo** [comment]
I'm kind surprised... doesn't this effectively mean that pnp is abandoned at the mid-term?

**Comment by coralm** [comment]
Initially I was able to get pnp4nagios to work except exporting to a PDF.  Some of the code in FPDF was deprecated.  I was able to update FPDF to the current release and, now, pnp4nagios is working with my Nagios system running PHP 7.

FPDF - http://www.fpdf.org/en/download.php
FPDI - https://www.setasign.com/products/fpdi/downloads/#files

Hope this may be of help to someone.

**Comment by cathode911** [comment]
So, does that mean that project is unmaintained? Latest ubuntu & debian for example have no pnp4nagios packages in official repos.

**Comment by aureq** [comment]
@lingej Since March 2016, is there any plan to support PHP7 or above? It would be great to have an idea so user can find an alternative if the project is not moving further.

Thank you.

**Comment by lingej** [comment]
Please use the latest code an report errors
