### ISSUE TITLE
graph for more than 1 year period

### ISSUE THREAD

**Issue by PetrMa** [lingej/pnp4nagios#131]
Hello,
is there any way, how to show by default on graphs page also graph for whole period, not only one year max? The whole period will show all historical data at the end of graph page.
I know that i can use Zoom on each graph, but I would like to see additional choise in menu:
_Custom time range
Overview
4 Hours
25 Hours
One Week
One Month
One Year_
**Whole period**

Can you help me please?
thanks, Petr

**Comment by lingej** [comment]
https://github.com/lingej/pnp4nagios/blob/master/sample-config/pnp/config.php.in#L209

**Comment by PetrMa** [comment]
Great, thanks.
This is exactly what I need.
