### ISSUE TITLE
pnp4nagios isn't able to plot graphs for OIDs which return output in octet-string format

### ISSUE THREAD

**Issue by abhishekans21** [lingej/pnp4nagios#145]
Hi,
I wanted to monitor CPU load for a remote host, so I wrote a service with OID .1.3.6.1.4.1.2021.10.1.3.1, this returns CPU load averaged per minute in octet-string format, pnp4nagios, however, wasn't able to plot a graph for the same, but when using OID .1.3.6.1.4.1.2021.10.1.5.1, which returns the same data but in integer format, graphs were easily plotted.

Thanks,
Abhishek.

**Comment by lingej** [comment]
please provide some perfdata output from both checks and the version of pnp4nagios you use

**Comment by abhishekans21** [comment]
pnp4nagios 0.6.26
For OID .1.3.6.1.4.1.2021.10.1.5.1 : SNMP OK - 108
For OID .1.3.6.1.4.1.2021.10.1.3.1: SNMP OK -"1.08"

Try doing ./check_snmp -H <ip_address>  -o <object_ID> with the above OIDs for some ip address(even localhost will do) to get this kind of output.

**Comment by lingej** [comment]
thats not a perfdata string!

please provide the complete output of check_snmp while testing

**Comment by abhishekans21** [comment]
![string_and_int output](https://user-images.githubusercontent.com/26730737/38099266-c3202e0c-3397-11e8-8bac-c1cc7a4cd039.png)
Please find the screenshot attached, it consists of output for both the OIDs.

**Comment by lingej** [comment]
no perfdata no graph!

not an pnp4nagios issue

**Comment by abhishekans21** [comment]
Am sorry am I missing something, I thought since the output is in string format pnp4nagios somehow not able to use it. Can you please clarify?

**Comment by lingej** [comment]
https://docs.pnp4nagios.org/pnp-0.6/about#system_requirements

docs section 1

**Comment by abhishekans21** [comment]
okay, thanks :) Am closing this issue.
