### ISSUE TITLE
Error to start pnp_gearman_worker service

### ISSUE THREAD

**Issue by misterpremium** [lingej/pnp4nagios#151]
Good morning

I trying to start the pnp_gearman worker service and I recive the next error

```
/etc/init.d/pnp_gearman_worker start
Starting pnp_gearman_worker Perl module Gearman::Worker not found
failed
```

I have installed that module 

```
perldoc -l Gearman::Worker
/usr/local/share/perl5/Gearman/Worker.pm


```
Im using CentOS 7.5, 

How can I fix this problem?

Thanks 

Regards

**Comment by dan-m-joh** [comment]
It looks like Worker.pm is not installed where pnp_gearman_worker can find it.

Could you try "perldoc -l Gearman::Worker" as the user you are trying to run the service as?
i.e."sudo -u nagios perldoc -l Gearman::Worker"

Here it looks like this:
```
# sudo -u nagios perldoc -l Gearman::Worker
/usr/share/perl5/vendor_perl/Gearman/Worker.pm
```
-- 
D/\N

**Comment by misterpremium** [comment]
Hi 

That is the result.
```
sudo -u nagios perldoc -l Gearman::Worker
/usr/local/share/perl5/Gearman/Worker.pm
```
Thanks
