### ISSUE TITLE
json.php prevents web interface from displaying graphs

### ISSUE THREAD

**Issue by gjcarter2** [lingej/pnp4nagios#167]
The following changes are suggested if you encounter the error:

PHP Deprecated:  Methods with the same name as their class will not be constructors in a future version of PHP; Services_JSON_Error has a deprecated constructor in /usr/local/pnp4nagios/share/application/lib/json.php on line

in json.php the following lines: 115, 781, 795
115 case:
function Services_JSON($use = 0)
with
function __construct($use = 0)
781 case:
function Services_JSON_Error($message = 'unknown error', $code = null, $mode = null, $options = null, $userinfo = null)
with
function __construct($message = 'unknown error', $code = null, $mode = null, $options = null, $userinfo = null)
795 case:
function Services_JSON_Error($message = 'unknown error', $code = null, $mode = null, $options = null, $userinfo = null)
with
function __construct($message = 'unknown error', $code = null, $mode = null, $options = null, $userinfo = null)

**Comment by rippiedoos** [comment]
I followed these instructions as I had the same warnings, worked perfectly! But I also get the error:
```
syntax error, unexpected 'Kohana' (T_STRING)

kohana/system/libraries/Input.php [60]:
```
Any hints?
