### ISSUE TITLE
Generating pdf file via terminal command

### ISSUE THREAD

**Issue by dustennL** [lingej/pnp4nagios#189]
Is it possible to generate a pdf report from host into a file by running a terminal command, instead of using the web interface to do it manually ? I'm trying to use the pdf feature to send reports via mail automatically.

**Comment by lingej** [comment]
Yes, that is possible!

Just download via webbrowser and watch the webserver logfile. You will easily find the correct url 

Joerg

**Comment by dustennL** [comment]
> Owner
Thank you so much for the reply !
Im running nagios in vm server with only terminal and i cant access a webbrowser from there.
I tried to use  "wget -o example.pdf  <url from web browser>" to generate the file and send it by email but the couldnt open it because was corrupted or baddly generated. I didnt know there was diferent urls.
If i download a pdf from a diferente machine in the network, can i still achieve your suggestion ( check the correct url from apache2 logs ) ?

**Comment by lingej** [comment]
use the pnp4nagios web interface to generate the pdf you need.

Examine the apache webserver access logfile. You will find the download URL there.

Use the URL to genereate your PDF files via wget or curl
