### ISSUE TITLE
pnp4nagios Nagios Graphs Not Loading Ubuntu 20.04

### ISSUE THREAD

**Issue by riteshkumar-patel** [lingej/pnp4nagios#190]
Hi Team,

Can't recall when this issue began but upon checking the graphs this week I noticed the graphs on all Nagios hosts were not loading. I did some troubleshooting but could not pinpoint the issue. Was wondering if someone can share some insight on this and what can be done to fix this?

PHP version: PHP 7.4.3 (cli) (built: Jun 13 2022 13:43:30) ( NTS )
Ubuntu 20.04
pnp4nagios version: pnp4nagios-0.6.26

<img width="617" alt="image" src="https://user-images.githubusercontent.com/104525180/178062629-671ec848-cd19-4270-a110-6ac40caef7be.png">

**Comment by iovcho** [comment]
Hello @riteshkumar-patel . Can you open browser console to see what exactly is the error for the loading the images? Just in case check the webserver logs too.

**Comment by riteshkumar-patel** [comment]
This is what I see in the logs when I click on the image:

`*.*.*.* - ritesh [11/Jul/2022:09:11:25 -0400] "GET /pnp4nagios/image?host=AD-E311&srv=_HOST_&view=4&source=0&start=1624713085&end=1657545085 HTTP/1.1" 200 1102 "https://*.*.com/pnp4nagios/graph?host=AD-E311&srv=_HOST_" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
*.*.*.* - ritesh [11/Jul/2022:09:11:25 -0400] "GET /pnp4nagios/image?host=AD-E311&srv=_HOST_&view=4&source=1&start=1624713085&end=1657545085 HTTP/1.1" 200 1102 "https://*.*.com/pnp4nagios/graph?host=AD-E311&srv=_HOST_" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
*.*.*.* - ritesh [11/Jul/2022:09:11:25 -0400] "GET /pnp4nagios/image?host=AD-E311&srv=_HOST_&view=2&source=0&start=1656915085&end=1657545085 HTTP/1.1" 200 1102 "https://*.*.com/pnp4nagios/graph?host=AD-E311&srv=_HOST_" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"
*.*.*.* - ritesh [11/Jul/2022:09:11:25 -0400] "POST /pnp4nagios//ajax/filter/set-sfilter HTTP/1.1" 200 360 "https://*.*.com/pnp4nagios/graph?host=AD-E311&srv=_HOST_" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36"`

**Comment by iovcho** [comment]
Hi, thanks for the webserver logs. Please check browser console for errors.

**Comment by riteshkumar-patel** [comment]
I don't see any errors coming up when I click on the image, also I turned on developer tools and I am not seeing anything being caught there too

**Comment by riteshkumar-patel** [comment]
@iovcho any other suggestions for this?

**Comment by riteshkumar-patel** [comment]
Fixed the issue ran this: sudo apt-get install -y rrdtool librrdp-perl php-gd php-xml
