### ISSUE TITLE
PNP=?

### ISSUE THREAD

**Issue by tjyang** [lingej/pnp4nagios#191]
@lingej or others

Please enlighten me(new comer) what PNP stand for ? 
ie, why pnp4nagios has a pnp prefix ?

**Comment by lingej** [comment]
pnp is not perfparse 

Perfparse was the first rrd based solution out there since nagios 0.x

joerg

**Comment by tjyang** [comment]
@lingej 
PNP= **P**np is **N**ot **P**erfparse , thanks for the explanation. 
Wish you have nice retired life, please stop to enlighten us where you are bored.

**Comment by tjyang** [comment]
> good question... I found the old documentation but couldn't find an answer either: https://web.archive.org/web/20211005052630/https://docs.pnp4nagios.org/

I also found the 0.6.25 is come with pnp4nagios-0.6.25 rpm. The one-page doc can be viewed from a nagios site like URL like http://nagios01.test.lan/pnp4nagios/docs/view/en_US/doc_complete , pnp4nagios is configured properly.
