### ISSUE TITLE
rrd_modify.pl not working ?

### ISSUE THREAD

**Issue by tatref** [lingej/pnp4nagios#58]
Hi,

I'm trying to use the rrd_modify.pl script to add datasources to an RRD (I would like to use variable number of datasources in my checks, so I need to add datasources to the RRD).

    # rrdtool info CPU_Load_test.rrd
    filename = "CPU_Load_test.rrd"
    rrd_version = "0003"
    step = 60
    last_update = 1370252515
    header_size = 5040
    ds[1].index = 0
    ds[1].type = "GAUGE"
    ds[1].minimal_heartbeat = 8460
    ds[1].min = NaN
    ds[1].max = NaN
    ds[1].last_ds = "1.870"
    ds[1].value = 1.0285000000e+02
    ds[1].unknown_sec = 0
    ds[2].index = 1
    ds[2].type = "GAUGE"
    ds[2].minimal_heartbeat = 8460
    ds[2].min = NaN
    ds[2].max = NaN
    ds[2].last_ds = "1.530"
    ds[2].value = 8.4150000000e+01
    ds[2].unknown_sec = 0
    ds[3].index = 2
    ds[3].type = "GAUGE"
    ds[3].minimal_heartbeat = 8460
    ds[3].min = NaN
    ds[3].max = NaN
    ds[3].last_ds = "1.050"
    ds[3].value = 5.7750000000e+01
    ds[3].unknown_sec = 0
    rra[0].cf = "AVERAGE"
    rra[0].rows = 2880
    ...

Here is what I tried:

    # ./rrd_modify.pl CPU_Load_test.rrd insert 4
    Use of uninitialized value in concatenation (.) or string at ./rrd_modify.pl line 227, <IFILE> line 48.
    Use of uninitialized value in concatenation (.) or string at ./rrd_modify.pl line 227, <IFILE> line 48.
    Use of uninitialized value in concatenation (.) or string at ./rrd_modify.pl line 227, <IFILE> line 48.
    ...

I also tried with the options insert 4,1 or 3 or 3,1... I still get the same output, and no file *.chg is generated, as stated in the help.

Am I doing something wrong, or is it a bug ?

**Comment by sporkman** [comment]
That change fixed it for me as well, perhaps someone could commit the above fix?

**Comment by tatref** [comment]
I found the workaround: just specify in the `pnp/etc/check_commands/wcheck_name_here>.cfg`
`RRD_STORAGE_TYPE = MULTIPLE`

npcd will create 1 RRD per datasource, so there is no need to change the RRD layout.
