### ISSUE TITLE
Would like to be able have have custom query string parameters in special template

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [lingej/pnp4nagios#97]
Hi,  I use a query string parameter called "&hostlike=<regex>" in my special template to generate a combined graph of all hosts matching this parameter.   This works great except for when i use the zoom functionality, the "hostlike" parameter is not passed into the query strings of the resulting pages and image URLs.

Is there any functionality that exists now for me to be able to pass this parameter?  

Thanks,

Jay

**Comment by lingej** [comment]
i dont want to add new functions to  pnp4nagios.

Use $_REQUEST instead
